### ISSUE TITLE
unable to resolve class com.cloudbees.groovy.cps.NonCPS

### ISSUE THREAD

**Issue by vinay-prasad** [jenkinsci/JenkinsPipelineUnit#116]
BUG! exception in phase 'semantic analysis' in source unit 'file:/C:\Users\3694805\workspace\eclipseneon\pipeline_example/Jenkinsfile' The lookup for com\test\model\AppUploadResponse.groovy caused a failed compilaton. There should not have been any compilation from this call.
	at org.codehaus.groovy.control.ClassNodeResolver.findByClassLoading(ClassNodeResolver.java:217)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:201)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:172)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader$3.findClassNode(GroovyScriptEngine.java:225)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:128)
	at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:684)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:321)
	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1247)
	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:175)
	at org.codehaus.groovy.control.CompilationUnit$13.call(CompilationUnit.java:673)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:948)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:615)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:564)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:299)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:269)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:256)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:243)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:255)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:212)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:568)
	at groovy.util.GroovyScriptEngine$loadScriptByName$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.loadScript(PipelineTestHelper.groovy:323)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$loadScript$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.lesfurets.jenkins.unit.BasePipelineTest.loadScript(BasePipelineTest.groovy:99)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at test.groovy.com.test.TestJenkinsfileJob.test(TestJenkinsfileJob.groovy:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
C:\Users\3694805\workspace\eclipseneon\pipeline_example\resources\shared-center@master\src\com\test\model\AppUploadResponse.groovy: -1: unable to resolve class com.cloudbees.groovy.cps.NonCPS
 @ line -1, column -1.
1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:312)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:963)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:615)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:564)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:299)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:269)
	at com.lesfurets.jenkins.unit.InterceptingGCL.super$5$parseClass(InterceptingGCL.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1224)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
	at com.lesfurets.jenkins.unit.InterceptingGCL.parseClass(InterceptingGCL.groovy:20)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:255)
	at groovy.lang.GroovyClassLoader.recompile(GroovyClassLoader.java:762)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:719)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:788)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:678)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:546)
	at org.codehaus.groovy.control.ClassNodeResolver.findByClassLoading(ClassNodeResolver.java:212)
	... 55 more

**Comment by vinay-prasad** [comment]
I am trying to use the framework to test my Jenkins pipeline using shared libraries. I am still taking the baby steps and going strictly as per the README. Have the jenkins-pipeline-unit-1.1.jar in my classpath and my test class extends the BasePipelineTest

import static org.junit.Assert.*

import org.junit.Before
import org.junit.Test

import com.lesfurets.jenkins.unit.BasePipelineTest
import static com.lesfurets.jenkins.unit.global.lib.LibraryConfiguration.library
import static com.lesfurets.jenkins.unit.global.lib.LocalSource.localSource

class TestJenkinsfileJob extends BasePipelineTest{


	@Override
	@Before
	void setUp() throws Exception {
		String dirPath = new File( "${System.getProperty('user.dir')}/resources")
				.getAbsoluteFile()
				.getAbsolutePath()

		println (dirPath);
		def library = library()
				.name('shared-center')
				.allowOverride(true)
				.implicit(false)
				.defaultVersion("master")
				.targetPath(dirPath)
				.retriever(localSource(dirPath))
				.build()
		helper.registerSharedLibrary(library)

		super.setUp()
	}
	@Test
	public void test() {
		def script = loadScript("Jenkinsfile")
		script.execute()
		printCallStack()
	}
}

But the Junit test fails with above stack trace.

**Comment by macg33zr** [comment]
It is hard to comment on a solution without seeing what you have in the Jenkinsfile and the AppUploadResponse.groovy. It is obviously something around use of NonCPS annotation. Have you tried changing your test to use runScript("Jenkinsfile")? I thought loadScript() was 'deprecated' in the latest version. If you look in the unit tests for JenkinsPipelineUnit there are some tests for the library scenarios, they are using 'runScript'. It was a change in the latest 1.1 version - see the release notes. Hope some of this might help.

**Comment by vinay-prasad** [comment]
Thanks for your response @macg33zr. Yes in 1.1 loadScript is deprecated. To fix the issue I had to add below dependency to the classpath
<dependency>
			<groupId>com.cloudbees</groupId>
			<artifactId>groovy-cps</artifactId>
			<version>1.1</version>
</dependency>

BasePipelineTest.class uses NonCPS 
Line : 13  Map<String, String> imports = ["NonCPS": "com.cloudbees.groovy.cps.NonCPS"]
