### ISSUE TITLE
Q: how to avoid errors on null objects (mock?)

### ISSUE THREAD

**Issue by TD-4242** [jenkinsci/JenkinsPipelineUnit#118]
In my pipeline I have a line set for production deployment jobs to be kept forever:

      currentBuild.rawBuild.keepLog(true)

this throws an exception in testing:

```
java.lang.NullPointerException: Cannot invoke method keepLog() on null object
	at approvalNeeded.call_closure1(approvalNeeded.groovy:19)
	at approvalNeeded.call_closure1(approvalNeeded.groovy)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.callClosure(PipelineTestHelper.groovy:472)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.callIfClosure(PipelineTestHelper.groovy:192)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure4.doCall(PipelineTestHelper.groovy:171)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure3.doCall(PipelineTestHelper.groovy:143)
	at approvalNeeded.call(approvalNeeded.groovy:13)
	at approvalNeeded.call(approvalNeeded.groovy:28)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.callMethod(PipelineTestHelper.groovy:156)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure3.doCall(PipelineTestHelper.groovy:143)
	at vars.notifyTestSpe.approvalNeeded.Test that a deployment does not happen if not approved(approvalNeededTestSpec.groovy:36)
```

I haven't found a way to mock that setting or ignore it somehow.  Sorry I'm pretty green to java/groovy testing.

**Comment by TD-4242** [comment]
Have another instance where the job spawns a build, then reports back the number from that build
```buildInfo = build( ... )

...

  echo "buildInfo.getNumber()"
```

I'm not sure how to mock the getNumber method or buildInfo object so I just end up with an error in unittest:

```
    java.lang.NullPointerException: Cannot invoke method getNumber() on null object
```

**Comment by chrismaes87** [comment]
for the build number, I am using `env.BUILD_NUMBER` which I can set before running the tests:

`binding.setVariable('env', [JOB_NAME:"test-job-name", BUILD_NUMBER: "123"])`

**Comment by stchar** [comment]
@TD-4242 
`currentBuild` is set by `BasePipelineTest `
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/8f1a57068561f09a6f76db278ef274e02c6accc9/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L78
So I suggest to use getter and setter of `binding` 
```
def currentBuild = binding.getVariable("currentBuild")
currentBuild.buildInfo = [keepLog:{"mock me"}]
binding.setVariable("currentBuild",currentBuild);
```

**Comment by stchar** [comment]
I'm closing the issue, please use gitter channel https://gitter.im/JenkinsPipelineUnit/Lobby if you have any questions like this one.
