### ISSUE TITLE
Unreadable exception on serialization error

### ISSUE THREAD

**Issue by sparshev** [jenkinsci/JenkinsPipelineUnit#160]
Hi Guys,

I found that it's really hard to get what's happening if we getting a serialization error during execution of the CPS tests:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.226 sec <<< FAILURE!
default_run(CPS1Test)  Time elapsed: 0.79 sec  <<< ERROR!
java.lang.Exception: com.cloudbees.groovy.cps.impl.BlockScopeEnv@7393222f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
...
Caused by: java.io.NotSerializableException: org.example.testsharedlib.TestClass
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1790)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

Of course it contains the caused by exception - but many ones can't find it and `com.cloudbees.groovy.cps.impl.BlockScopeEnv@7393222f` is not helping to locate the place of exception.

Maybe it will be better to slightly modify the PipelineHelperCPS to get the next result:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.116 sec <<< FAILURE!
default_run(CPS2Test)  Time elapsed: 0.75 sec  <<< ERROR!
java.lang.Exception: Unable to serialize locals [test_obj:org.example.testsharedlib.TestClass@6d167f58] in test
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
...
Caused by: java.io.NotSerializableException: org.example.testsharedlib.TestClass
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
...
```

Looks much better and more clean for the end user. Or at least remove the try to capture the exception - it makes no sense.

Context shared library attached: [test_shared_lib-JenkinsPipelineUnit-160.zip](https://github.com/jenkinsci/JenkinsPipelineUnit/files/3812182/test_shared_lib-JenkinsPipelineUnit-160.zip)

**Comment by sparshev** [comment]
The attached context with modification is working only for BlockScopeEnv - but I think it's not a big deal to get the required info from each possible Env object.

**Comment by sparshev** [comment]
Yeah, I tried - it's not so simple, but the next catch will make our life easier for sure - it will say where the serialization error happened:
```
} catch (exception) {
    throw new Exception("Exception during serialization in `${next.e.closureOwner().class.name}` for class ${exception.getMessage()}", exception)
}
```
