### ISSUE TITLE
DeclarativePipelineTest - 'aborted' post step not working

### ISSUE THREAD

**Issue by topalach** [jenkinsci/JenkinsPipelineUnit#211]
I'm using `DeclarativePipelineTest` and trying to run a script with the `aborted` post stage. Unfortunately, I get this error:
```
No signature of method: com.lesfurets.jenkins.unit.declarative.PostDeclaration.aborted() is applicable for argument types: (Jenkinsfile$_run_closure1$_closure4$_closure8) values: [Jenkinsfile$_run_closure1$_closure4$_closure8@330be0c4]
groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.declarative.PostDeclaration.aborted() is applicable for argument types: (Jenkinsfile$_run_closure1$_closure4$_closure8) values: [Jenkinsfile$_run_closure1$_closure4$_closure8@330be0c4]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:76)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at Jenkinsfile$_run_closure1$_closure4.doCall(Jenkinsfile:19)
...
```

It seems that a handful of `post` steps are not defined in the `PostDeclaration` class
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/declarative/PostDeclaration.groovy

Is that correct? Is there a workaround?

Minimal repro scenario:
Pipeline script:
```
pipeline {
  agent any

  stages {
    stage ('test') {
      steps {
        echo 'test'
      }
    }
  }

  post {
    always {
      echo 'always'
    }
    aborted {
      echo 'aborted'
    }
  }
}
```

Test script:
```
import com.lesfurets.jenkins.unit.declarative.DeclarativePipelineTest
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class SomeTest extends DeclarativePipelineTest {
  @Override
  @BeforeEach
  void setUp() throws Exception {
    super.setUp()
  }

  @Test
  void executes_script() {
    runScript('Jenkinsfile')
  }
}
```

**Comment by stchar** [comment]
Yep it is lack of implementation.
`PostDeclaration` should be extended, I cannot see any workarounds rather then patch it and deploy to local maven.

**Comment by topalach** [comment]
Submitted the following PR:
https://github.com/jenkinsci/JenkinsPipelineUnit/pull/212
Maybe it will work?
