### ISSUE TITLE
DeclarativePipelineTest - 'docker' is missing the common option for 'reuseNode'

### ISSUE THREAD

**Issue by pcoulso1** [jenkinsci/JenkinsPipelineUnit#217]
The class DockerDeclaration in com.lesfurets.jenkins.unit.declarative.AgentDeclaration seems to be missing the common option for 'reuseNode'

e.g. when used in the stage section of the jenkinsfile

```
    stage('build') {
      agent {
        docker {
          image "myImage:1.0.0"
          label 'docker'
          reuseNode true
        }
      }
```
 
And results in the following exception when the tests are run
 
```
java.lang.NullPointerException
            at Jenkinsfile$_run_closure1$_closure6$_closure11.closure20$_closure23(Jenkinsfile:148)
            at Jenkinsfile$_run_closure1$_closure6$_closure11.closure20$_closure23(Jenkinsfile)
            at com.lesfurets.jenkins.unit.declarative.DeclarativePipeline.createComponent(DeclarativePipeline.groovy:18)
            at com.lesfurets.jenkins.unit.declarative.AgentDeclaration.docker(AgentDeclaration.groovy:41)
            at Jenkinsfile$_run_closure1$_closure6.closure11$_closure20(Jenkinsfile:144)
```

See [https://www.jenkins.io/doc/book/pipeline/syntax/](https://www.jenkins.io/doc/book/pipeline/syntax/) for details

**Comment by nre-ableton** [comment]
If I'm not mistaken, this functionality is provided by the Docker plugin. I don't think it's appropriate for JenkinsPipelineUnit to test steps provided by other plugins, or else it could become quite bloated.

One could make the argument that we should make an exception for this particular plugin, since it's quite commonly used (I don't recall -- does Blue Ocean depend on the Docker plugin? 🤔).

In the meantime, I would suggest mocking the `docker` step in your test class runner as a workaround. The [jenkins-pipeline-mocks](https://github.com/AbletonDevTools/jenkins-pipeline-mocks) library also provides a `docker` mock, but I am not sure if it would work for declarative pipelines, as that library has only been tested with scripted pipelines.

**Comment by stchar** [comment]
@pcoulso1 
declarative pipeline has lack of some features, If would you have a willing to submit a PR?
