### ISSUE TITLE
DeclarativePipelineTest - 'when' is missing the option for 'anyOf' and 'allOf'

### ISSUE THREAD

**Issue by pcoulso1** [jenkinsci/JenkinsPipelineUnit#227]
The class WhenDeclaration in com.lesfurets.jenkins.unit.declarative seems to be missing the option for 'anyOf' and 'allOf'

e.g. when used in the stage section of the jenkinsfile
```
stage('build') {
  when {
    allOf {
      environment name: 'cleanBuild', value: 'true'
      expression { BRANCH_NAME ==~ /(develop|hotfix\/.*)/ }
    }
  }
  steps {
    …
  }
}
```	  
And results in the following exception when the tests are run
```
groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.declarative.WhenDeclaration.allOf() is applicable for argument types: (Jenkinsfile$_run_closure1$_closure6$_closure11$_closure21$_closure24) values: [Jenkinsfile$_run_closure1$_closure6$_closure11$_closure21$_closure24@4149c063]
Possible solutions: any(), sleep(long), any(groovy.lang.Closure), split(groovy.lang.Closure)
            at Jenkinsfile$_run_closure1$_closure6.closure11$_closure21(Jenkinsfile:153)
            at Jenkinsfile$_run_closure1$_closure6.closure11$_closure21(Jenkinsfile)
            at com.lesfurets.jenkins.unit.declarative.DeclarativePipeline.createComponent(DeclarativePipeline.groovy:18)
            at com.lesfurets.jenkins.unit.declarative.StageDeclaration.when(StageDeclaration.groovy:32)
            at Jenkinsfile$_run_closure1.closure6$_closure11(Jenkinsfile:152)
```
See https://www.jenkins.io/doc/book/pipeline/syntax/ for details

**Comment by lucasvc** [comment]
Is there any way to workaround this in my own test code?
I have tried,

```
        testee = loadScript("vars/mypipeline.groovy")
        helper.registerAllowedMethod("anyOf", [Closure.class], { it -> it() })
        testee.call()
```
But still same exception.

Sorry if this is somewhere explained, but I could not find it and I'm totally groovy-newbie.

**Comment by epsilo** [comment]
Hi @IuryAlves 

The implementation of anyOf you made only work for a single validation inside anyOf.
`anyOf { branch 'master' }`
In this case works to check if the branch is master or not.

If we have more than one validation e will only validate the last one
`anyOf { branch 'master'; branch 'release'; branch 'develop' }`
In this case if the branch is master it will be false, but if is develop e will be true.

Do you know how to make this to work as a "anyOf" behaviour

**Comment by IuryAlves** [comment]
Hey  @epsilo 

You're right!

I have done a new [PR](https://github.com/jenkinsci/JenkinsPipelineUnit/pull/278) for adding support to multiple validations for `branch` and `expression`.

Bear in mind that there are others validations still missing.

**Comment by epsilo** [comment]
Thank you very much!

**Comment by IuryAlves** [comment]
@epsilo My PR was merged. Can you try again?

**Comment by epsilo** [comment]
@IuryAlves it is working great now!
Thanks

**Comment by IuryAlves** [comment]
Nice. I think this issue can be closed now.

**Comment by jcmendez-guerrero** [comment]
Technically The issue covered BeforeAgent as well which is not implemented yet, therefore the issue might be still open

**Comment by jordarlu** [comment]
Hi, Just wondering if any update on the issue to support BeforeAgent?  the left issue quoted by @jcmendez-guerrero .. Thanks!

**Comment by MKITConsulting** [comment]
I faced the same problems and created a pull request to solve the issue.

**Comment by MKITConsulting** [comment]
Thx for merging @nre-ableton. I guess we can close this issue here. Any plans on when a new tag will be created?

**Comment by nre-ableton** [comment]
> Thx for merging @nre-ableton. I guess we can close this issue here. Any plans on when a new tag will be created?

I'll try to make a release sometime this week when I have some time.
