### ISSUE TITLE
Unable to serialize locals UNKNOWN in `class com.lesfurets.jenkins.unit.cps.MockClosure`

### ISSUE THREAD

**Issue by PhilippHomann** [jenkinsci/JenkinsPipelineUnit#251]
Hey,

I'm trying to test my pipeline library using the `BasePipelineTestCPS`.
When calling a simple script with a body I receive the error above.

unknownTest.groovy:
```groovy
import com.lesfurets.jenkins.unit.cps.BasePipelineTestCPS

import org.junit.Test
import org.junit.Before

class unknownTest extends BasePipelineTestCPS {
	@Before
	void setUp() {
		super.setUp()
	}

	@Test
	void withoutBody() {
		Script s = loadScript("vars/unknown.groovy")
		s.call("world")
		printCallStack()
	}

	@Test
	void withBody() {
		Script s = loadScript("vars/unknown.groovy")
		s.call("world") {}
		printCallStack()
	}
}
```

vars/unknown.groovy
```groovy
void call(String world, Closure body = null) {
	node("master") {
		echo "Hello ${world}"
		if(body)
			body()
	}
}
```

Output:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running unknownTest
Hello world
   unknown.call(world)
      unknown.node(master, groovy.lang.Closure)
         unknown.echo(Hello world)
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.431 sec <<< FAILURE! - in unknownTest
withBody(unknownTest)  Time elapsed: 0.152 sec  <<< ERROR!
java.lang.RuntimeException: Unable to serialize locals UNKNOWN in `class com.lesfurets.jenkins.unit.cps.MockClosure`
	at unknownTest.withBody(unknownTest.groovy:22)
Caused by: java.io.NotSerializableException: unknownTest
	at unknownTest.withBody(unknownTest.groovy:22)


Results :

Tests in error: 
  unknownTest.withBody:22 » Runtime Unable to serialize locals UNKNOWN in `class...

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
```

Am I doing anything wrong? Do I have to wrap my Closure somehow?

**Comment by stchar** [comment]
hi @PhilippHomann, first you need to load your library
https://github.com/jenkinsci/JenkinsPipelineUnit#localsource-retriever

Then in your pipeline you need to load it with @Library annotation, and only after that you can call vars. If you need any examples, please see tests in this repo. There is also a set of lnks for demo projects in the bottom of the Readme

**Comment by PhilippHomann** [comment]
Thanks for that hint. Will give it a try!
