### ISSUE TITLE
No such property: AGENT_LABEL in AgentDeclaration when variable used from script scope

### ISSUE THREAD

**Issue by ballab1** [jenkinsci/JenkinsPipelineUnit#272]
MissingPropertyException occurrs when using a variable defined at the script scope
'def AGENT_LABEL = "someLabel"
pipeline {
    agent AGENT_LABEL
    stages {  }
}'

the error reported is as follows:
`groovy.lang.MissingPropertyException: No such property: AGENT_LABEL for class: com.lesfurets.jenkins.unit.declarative.AgentDeclaration
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
	at DevStaging-Jenkinsfile$_run_closure1$_closure2.doCall(DevStaging-Jenkinsfile:22)
	at DevStaging-Jenkinsfile$_run_closure1$_closure2.doCall(DevStaging-Jenkinsfile)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.lesfurets.jenkins.unit.declarative.GenericPipelineDeclaration.createComponent(GenericPipelineDeclaration.groovy:23)`

Submitted PR #273 to fix this

**Comment by stchar** [comment]
Hi @ballab1, thank you for the PR,  you might have merge conflicts with #271, I'm going to merge your PR right after 271.

**Comment by ballab1** [comment]
sounds good. I have no issue resolving any conflicts
