### ISSUE TITLE
[BUG] Timeout mock error since 1.5

### ISSUE THREAD

**Issue by philippart-s** [jenkinsci/JenkinsPipelineUnit#274]
Hello,

Since the 1.5 version of the framework the timeout mock doesn't work.

The code under test:
```groovy
steps.timeout(time: 1, unit: 'MINUTES') {
   steps.echo 'Should work !'
}
```
The error:
```
groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.BasePipelineTest$_registerAllowedMethods_closure19.call() is applicable for argument types: ([Ljava.lang.Object;) values: [[[time:1, unit:MINUTES], fr.hm.pichm.common.util.HttpUtil$_getHttpResponseContent_closure2@2b27cc70]]
Possible solutions: any(), any(), doCall(groovy.lang.Closure), any(groovy.lang.Closure), use([Ljava.lang.Object;), each(groovy.lang.Closure)

	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:286)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:812)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.callClosure(PipelineTestHelper.groovy:530)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure3.doCall(PipelineTestHelper.groovy:160)
```

The register method change in 1.5:

```groovy
helper.registerAllowedMethod('timeout', [Map])
helper.registerAllowedMethod('timeout', [Map, Closure]) { Map args, Closure c ->
     c.delegate = delegate
     helper.callClosure(c)
}
```

In 1.3:
```groovy
helper.registerAllowedMethod("timeout", [Map.class, Closure.class], null)
```

**Comment by nre-ableton** [comment]
Thanks for the bug report! Seems like a simple syntax error. See https://github.com/jenkinsci/JenkinsPipelineUnit/pull/275.
