### ISSUE TITLE
'java.lang.LinkageError: loader constraint violation' using 'BaseRegressionTest'

### ISSUE THREAD

**Issue by jgsogo** [jenkinsci/JenkinsPipelineUnit#307]
Hi! First of all, thanks again for this test framework, it is helping us a lot to develop our shared library. Kudos to creators and maintainers.

We are trying to move to a new CI (new Jenkinsfiles, new docker images,...) to run our test suite and we are facing an error we are not able to fix. I'm so sorry because I cannot share here all the project, but I'll try to post the relevant bits and see if anyone can help, I'm at the point of giving up and block the move to the new CI.

We have a repository with a shared library, and we are testing that shared library, project structure looks like:

```
build.gradle
gradle/wrapper/...
gradlew
jobs/build_single_reference.jenkins
resources/...
settings.gradle
src/org/jfrog/c3i/artifactory/ArtifactoryRepoInstance
src/...
test/test_jobs/BuildSingleReferenceTest.groovy
```

**gradle/wrapper/gradle-wrapper.properties**
```
#Thu Feb 21 14:28:04 CET 2019
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.2.1-all.zip
```

**build.gradle**
```groovy
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Groovy project to get you started.
 * For more details take a look at the Groovy Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.2.1/userguide/tutorial_groovy_projects.html
 */

plugins {
    // Apply the groovy plugin to add support for Groovy
    id 'groovy'
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven { url 'https://repo.jenkins-ci.org/releases/' }
}

dependencies {
    // Use the latest Groovy version for building this library
    implementation 'org.codehaus.groovy:groovy-all:2.4.12'

    // Use the awesome Spock testing and specification framework
    testImplementation 'org.spockframework:spock-core:1.2-groovy-2.4'

    // https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
    testCompile group: 'ch.qos.logback', name: 'logback-classic', version: '0.9.26'

    // Owner deps
    compile 'org.jfrog.artifactory.client:artifactory-java-client-services:+'
    compile group: 'org.yaml', name: 'snakeyaml', version: '1.8'

    // https://mvnrepository.com/artifact/org.kohsuke.stapler/json-lib
    compile group: 'org.kohsuke.stapler', name: 'json-lib', version: '2.4-jenkins-2'

    // Testing using JenkinsPipelineUnit
    testCompile 'org.assertj:assertj-core:3.15+' // <-- https://github.com/jenkinsci/JenkinsPipelineUnit/issues/209
    testCompile "com.lesfurets:jenkins-pipeline-unit:1.5"

    // https://mvnrepository.com/artifact/io.github.java-diff-utils/java-diff-utils
    testCompile group: 'io.github.java-diff-utils', name: 'java-diff-utils', version: '4.7'

    testImplementation 'org.mockito:mockito-core:3.5.7'
    testImplementation 'org.powermock:powermock-api-mockito2:2.0.7'
    testImplementation 'org.powermock:powermock-module-junit4:2.0.7'
    testImplementation 'org.powermock:powermock-module-junit4-rule-agent:2.0.7'
}

sourceSets {
    main {
        groovy {
            srcDirs = ['src']
        }
    }

    test {
        groovy {
            srcDirs = ['test']
        }
    }
}

test {
    jvmArgs '-Djdk.attach.allowAttachSelf=true'

    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat = 'full'
    }
    afterSuite { desc, result ->
        if (!desc.parent) { // will match the outermost suite
            println "Results: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} successes, ${result.failedTestCount} failures, ${result.skippedTestCount} skipped)"
        }
    }
}
```

**test/test_jobs/BuildSingleReferenceTest.groovy**
```groovy
class BuildSingleReferenceTest extends BaseRegressionTest {
    @Before
    void setUp() {
        super.setUp()

        println "1".repeat(100)
        def library = library().name('c3i')
                .defaultVersion('<notNeeded>')
                .allowOverride(true)
                .implicit(false)
                .targetPath('<notNeeded>')
                .retriever(projectSource())
                .build()
        helper.registerSharedLibrary(library)
        println "2".repeat(100)
    }

    @Test
    void testReferenceRequired() {
        println "3".repeat(100)
        def script = loadScript("jobs/build_single_reference.jenkins")
        // Error is raised from the previous function
        println "4".repeat(100)
    }
}
```

**jobs/build_single_reference.jenkins**
```groovy
#!groovy​

@Library('c3i') _

node("linux") {
}
```

This is the error I get when running from inside IntelliJ:

```
> Task :cleanTest
> Task :compileJava NO-SOURCE
> Task :compileGroovy UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/jgsogo/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.15/423a17aeb2f64bc6f76e8e44265a548bec80fd42/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
Loading shared library c3i with version <notNeeded>

loader constraint violation: loader groovy.lang.GroovyClassLoader$InnerLoader @359483b9 wants to load class org.jfrog.c3i.artifactory.ArtifactoryRepoInstance. A different class with the same name was previously loaded by 'app'. (org.jfrog.c3i.artifactory.ArtifactoryRepoInstance is in unnamed module of loader 'app')
java.lang.LinkageError: loader constraint violation: loader groovy.lang.GroovyClassLoader$InnerLoader @359483b9 wants to load class org.jfrog.c3i.artifactory.ArtifactoryRepoInstance. A different class with the same name was previously loaded by 'app'. (org.jfrog.c3i.artifactory.ArtifactoryRepoInstance is in unnamed module of loader 'app')
```

<details>
  <summary>Click to expand full traceback</summary>

```
> Task :cleanTest
> Task :compileJava NO-SOURCE
> Task :compileGroovy UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/jgsogo/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.15/423a17aeb2f64bc6f76e8e44265a548bec80fd42/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
Loading shared library c3i with version <notNeeded>

loader constraint violation: loader groovy.lang.GroovyClassLoader$InnerLoader @359483b9 wants to load class org.jfrog.c3i.artifactory.ArtifactoryRepoInstance. A different class with the same name was previously loaded by 'app'. (org.jfrog.c3i.artifactory.ArtifactoryRepoInstance is in unnamed module of loader 'app')
java.lang.LinkageError: loader constraint violation: loader groovy.lang.GroovyClassLoader$InnerLoader @359483b9 wants to load class org.jfrog.c3i.artifactory.ArtifactoryRepoInstance. A different class with the same name was previously loaded by 'app'. (org.jfrog.c3i.artifactory.ArtifactoryRepoInstance is in unnamed module of loader 'app')
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
	at java.base/java.lang.Class.getMethods(Class.java:1904)
	at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:71)
	at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:71)
	at java.desktop/java.beans.Introspector.getTargetMethodInfo(Introspector.java:1046)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:462)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:205)
	at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3328)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3326)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3303)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:289)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:331)
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.<init>(ClassMetaClassGetPropertySite.java:37)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createClassMetaClassGetPropertySite(AbstractCallSite.java:376)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGetPropertySite(AbstractCallSite.java:328)
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.acceptGetProperty(ClassMetaClassGetPropertySite.java:43)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:299)
	at com.lesfurets.jenkins.unit.InterceptingGCL.parseClass(InterceptingGCL.groovy:42)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:279)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:219)
	at com.lesfurets.jenkins.unit.global.lib.LibraryLoader$_doLoadLibrary_closure4$_closure10.doCall(LibraryLoader.groovy:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1152)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1150)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1150)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1150)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1150)
	at com.lesfurets.jenkins.unit.global.lib.LibraryLoader$_doLoadLibrary_closure4.doCall(LibraryLoader.groovy:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy22.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.lesfurets.jenkins.unit.global.lib.LibraryLoader.doLoadLibrary(LibraryLoader.groovy:88)
	at com.lesfurets.jenkins.unit.global.lib.LibraryLoader.loadLibrary(LibraryLoader.groovy:71)
	at com.lesfurets.jenkins.unit.global.lib.LibraryAnnotationTransformer$_call_closure1.doCall(LibraryAnnotationTransformer.groovy:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy22.accept(Unknown Source)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1039)
	at com.lesfurets.jenkins.unit.global.lib.LibraryAnnotationTransformer.call(LibraryAnnotationTransformer.groovy:73)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1087)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:250)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:237)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:279)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:236)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:562)
	at groovy.util.GroovyScriptEngine$loadScriptByName$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.loadScript(PipelineTestHelper.groovy:373)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$loadScript$5.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.lesfurets.jenkins.unit.BasePipelineTest.loadScript(BasePipelineTest.groovy:232)
	at com.lesfurets.jenkins.unit.BasePipelineTest$loadScript.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at test_jobs.BuildSingleReferenceTest.testReferenceRequired(BuildSingleReferenceTest.groovy:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

From my understanding, the class `ArtifactoryRepoInstance` has already been loaded (by 'app', what is 'app'?) as a consequence of the `helper.registerSharedLibrary(library)` call. And then, under the `loadScript("jobs/build_single_reference.jenkins")`, the call to `@Library('c3i') _` is loading everything again.

Right now there are no globals in my shared library (no `vars/` files, I've removed them trying to isolate this issue).

I would really appreciate any help, hint, workaround,... to move forward. Mid-term I can consider a refactor of all the project (dependencies, directories, imports,...) but right now we'd want to move everything as it is to the new CI. 

---

<details>
 <summary>PS.- this is the Jenkinsfile we are using in the new CI to run these tests:</summary>

```groovy
String artifactoryImage = 'docker.bintray.io/jfrog/artifactory-pro:6.10.2'

def withDockerNetwork(Closure inner) {
    try {
        networkId = UUID.randomUUID().toString()
        sh "docker network create ${networkId}"
        inner.call(networkId)
    } finally {
        sh "docker network rm ${networkId}"
    }
}


node("Linux") {
    stage("Checkout the sources") {
        checkout scm
    }

    stage("Tests that require Artifactory") {
        withCredentials([string(credentialsId: 'ART_LICENSE', variable: 'ART_LICENSE')]) {
            withDockerNetwork { n ->
                String artifactoryName = "rt${env.BUILD_NUMBER}"
                docker.image(artifactoryImage).withRun("-e ART_LICENSE=${env.ART_LICENSE} --network ${n} --name ${artifactoryName}") { c ->
                    docker.image('gradle:latest').inside("--network ${n}") {
                        // Install required utils  // TODO: We want a docker image with all of this
                        sh 'apt-get update'
                        sh 'apt-get install -y python3 python3-pip'

                        // Wait for Artifactory to be ready
                        timeout(time: 2, unit: 'MINUTES') {
                            waitUntil(initialRecurrencePeriod: 10000, quiet: true) {
                                int output = sh(script: "curl -s --fail http://${artifactoryName}:8081/artifactory/api/system/ping", returnStatus: true)
                                return output == 0
                            }
                        }

                        // Check we can do something with it
                        sh "curl -v -u admin:password http://${artifactoryName}:8081/artifactory/api/system/ping"

                        // Run the tests
                        withEnv(["ARTIFACTORY_URL=http://${artifactoryName}:8081/artifactory"]) {
                            sh './gradlew clean build test --info --tests test_jobs.BuildSingleReferenceTest'
                        }
                    }
                }
            }
        }
    }
}
```

</details>

**Comment by jgsogo** [comment]
I was able to work around this issue by refactoring the library and getting rid of some classes and imports.

**Comment by ls-julien-deruere** [comment]
I have same problem with Jackon:
`java.lang.LinkageError: loader constraint violation: loader (instance of org/jenkinsci/plugins/workflow/cps/CpsGroovyShell$CleanGroovyClassLoader) previously initiated loading for a different type with name "com/fasterxml/jackson/core/JsonParser"`
Probably because of Jackson2 API plugin installed. Is there a workaround?

**Comment by renanqts** [comment]
@ls-julien-deruere  try
```
helper.libLoader.preloadLibraryClasses = false
```
