### ISSUE TITLE
Declarative pipeline: "params" is null inside "environment" block

### ISSUE THREAD

**Issue by stefano-m** [jenkinsci/JenkinsPipelineUnit#391]
Hello, and thanks for this useful library.

### Version report

JenkinsPipelineUnit version 1.9

### Reproduction steps

Consider the below `Jenkinsfile`

``` groovy
pipeline {
    agent none
    parameters {
        string name: 'VERSION', defaultValue: 'default-version'
    }
    environment {
        VERSION = "${VERSION}"  // see stage block below
        // VERSION = "${params.VERSION}" // NullPointerException: Cannot get property 'VERSION' on null object
    }
    stages {
        stage('Print VERSION') {
            steps {
                echo env.VERSION // null when VERSION = "${VERSION}"  
                echo VERSION // default-version when VERSION = "${VERSION}"  
            }
        }
    }
}

```

When ran in a declarative pipeline test, if `VERSION` in the `environment` block is assigned to `params.VERSION`, the test will fail with ` java.lang.NullPointerException: Cannot get property 'VERSION' on null object`.

Instead, if `VERSION`  in the `environment` block is assigned to *just* `VERSION`, the pipeline will succeed **but** `env.VERSION` will be `null` rather than assuming the default value (this is possibly another bug, let me know if I should file it separately).

### Results

Expected result:

When `VERSION = "${params.VERSION}"`, the stage echoes the default value

Actual result:

When `VERSION = "${params.VERSION}"`, the pipeline fails with `NullPointerException: Cannot get property 'VERSION' on null object`.

Stack trace:

```
java.lang.NullPointerException: Cannot get property 'VERSION' on null object
	at example.run_closure1$_closure3(example.pipeline:8)
	at example.run_closure1$_closure3(example.pipeline)
	at com.lesfurets.jenkins.unit.declarative.GenericPipelineDeclaration.execute(GenericPipelineDeclaration.groovy:107)
	at com.lesfurets.jenkins.unit.declarative.DeclarativePipeline.execute(DeclarativePipeline.groovy:48)
	at com.lesfurets.jenkins.unit.declarative.DeclarativePipelineTest$_closure1.doCall(DeclarativePipelineTest.groovy:12)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.callClosure(PipelineTestHelper.groovy:572)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure3.doCall(PipelineTestHelper.groovy:187)
	at example.run(example.pipeline:1)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.callMethod(PipelineTestHelper.groovy:205)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure3.doCall(PipelineTestHelper.groovy:192)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.runScriptInternal(PipelineTestHelper.groovy:445)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.runScript(PipelineTestHelper.groovy:418)
	at com.lesfurets.jenkins.unit.BasePipelineTest.runScript(BasePipelineTest.groovy:340)

```

### Analysis

AFAIU, the issue is in `GenericPipelineDeclaration.execute()` where the `delegate` passed to `cl.rehydrate` does not have any `params` set. I'm not too familiar with the codebase though, and this is a guess based on the stack trace.

https://github.com/jenkinsci/JenkinsPipelineUnit/blob/2ad9665d0d6f9d1d81332d3af3dad42cf985edba/src/main/groovy/com/lesfurets/jenkins/unit/declarative/GenericPipelineDeclaration.groovy#L105

**Comment by stefano-m** [comment]
Possibly related to #387

**Comment by stefano-m** [comment]
While debugging, the NPE does not happen if we do

``` groovy
def cl = this.environment.rehydrate(delegate, env, this) 
```

although I'm not sure it's the right thing to do.

Also, I found a workaround, although it's not ideal: add `params` to the `env` map so it's not `null`.

I use the below helper method in my test class during set up to "fix" this issue.

``` groovy
    /**
     * Workaround for https://github.com/jenkinsci/JenkinsPipelineUnit/issues/391
     */
    void addParamsToEnv() {

        if (!binding.hasVariable('env')) {
            binding.setVariable('env', [:])
        }

        (binding.getVariable('env') as Map).with {
            params = this.binding.getVariable('params') as Map
        }
    }
```

**Comment by ksubileau** [comment]
It seems that this bug was fixed in version 1.16 by commit d2f4f528, is that right?
