### ISSUE TITLE
Not able to Mock Another Script

### ISSUE THREAD

**Issue by waytoharish** [jenkinsci/JenkinsPipelineUnit#401]
I have written a test Case to test the functionality but facing issue when calling a internal Script
1- javaDeployModule.groovy
#!/usr/bin/groovy

def call(body) {
    println(">>>>>>>>>>>00000"+body.toString())
    // evaluate the body block, and collect configuration into the object
    def config = [:]
    body.resolveStrategy = Closure.DELEGATE_FIRST
    body.delegate = config
    body()

    println(">>>>>>>>>>aaa0"+config)

    def myUtils = new com.aexp.jenkins.library.Utils()
    def configs = new com.aexp.jenkins.library.Configs()

    def pomVersion = config.versionNumber
   // def notify = new notification()
    env.START_TIME = myUtils.currentTime
    def buildGoals

    try {
        if (fileExists('pom.xml') | (config.pomLocation !=null) ) {
            println(">>>>>>>>>>>00000    "+config.versionNumber)
            if (config.versionNumber == null) {
                if (config.pomLocation != null) {
                    pomVersion = mavenUtils.getVersionName(config.pomLocation)
                } else {
                    pomVersion = mavenUtils.getVersionName('pom.xml')
                }
            }
            //Checking for the version tag availability
            println(">>>>>>>>>>>2222   "+myUtils.currentTime)
            if (config.pomLocation != null) {
                println(">>>>>>>>>>>3333   "+myUtils.currentTime)
                isVersionExist = mavenUtils.isVersionExist(config.pomLocation)
            } else {
                println(">>>>>>>>>>>444  "+myUtils.currentTime)
                isVersionExist = mavenUtils.isVersionExist('pom.xml')
            }

            try {
                // setting the new version based on version tag availability
                if (isVersionExist) {
                    println(">>>>>>>>>>>555  "+myUtils.currentTime)
                    log.info("We will set version number as - ${pomVersion}")
                    buildGoals = config.pomLocation !=null ? "versions:set -DnewVersion=${pomVersion} -f ${config.pomLocation}" : "versions:set -DnewVersion=${pomVersion}"
                    mavenBuild(buildGoals)
                }
            } catch (err) {
                currentBuild.result = 'FAILED'
                env.slackURL ? notify.notifyError() : ''
                updateDB("Java_Deploy")
                log.error("Unable to set version number via Maven. Error: \n${err}")
                return
            }

            def mavenProfile = config.mvnProfile != null ? " -P ${config.mvnProfile}" : ""
            buildGoals = config.goals != null ? config.goals : configs.defaultMavenModuleGoals
            buildGoals = config.pomLocation !=null ? " -f ${config.pomLocation} ${buildGoals}" : "${buildGoals}"
            buildGoals += mavenProfile
            // Added as part of ECCC-8197. Invoke failBuildIfSecretsExistsInSCMRepo() function to validate if secrets exists in SCM repo or not
            myUtils.failBuildIfSecretsExistsInSCMRepo()
            mavenBuild(buildGoals)
            currentBuild.result = 'SUCCESS'
            env.slackURL ? notify.notifyBuild() : ''
            updateDB("Java_Deploy")
        } else if (fileExists('gradlew')) {
            //Get project version from gradle.properties
            def v = config.versionNumber ?: gradleUtils.getVersion()
            log.info("Will set version number as - ${v}")
            buildGoals = config.goals != null ? config.goals : configs.defaultGradleModuleGoals
            buildGoals += " -PprojVersion=${v} "
            // Added as part of ECCC-8197. Invoke failBuildIfSecretsExistsInSCMRepo() function to validate if secrets exists in SCM repo or not
            myUtils.failBuildIfSecretsExistsInSCMRepo()
            gradleBuild(buildGoals)
            currentBuild.result = 'SUCCESS'
            env.slackURL ? notify.notifyBuild() : ''
            updateDB("Java_Deploy")
        } else {
            log.error("MUP_DPY_501","Missing build file. Expecting 'pom.xml' or 'gradlew'.")
            return
        }

        // Save artifactURL to Environment Varilable, this will store only if artifact is tar.gz as of now
        myUtils.saveArtifactURL()

    }catch(err){
        currentBuild.result = 'FAILED'
        env.slackURL ? notify.notifyError() : ''
        println "error>>>>>>>>>>>" +err.getMessage();
        updateDB("Java_Deploy")

       // log.error("MUP_DPY_500",'maven Deploy FAILED'+err.getMessage())
    }
}

2- mavenUtils.groovy
#!/usr/bin/groovy

/**
 * Call Maven with desired goal
 * @param goals
 */
def run(String goals) {
  String maven = "mvn -B"
    if (wrapperAvailable()) {
        println "Using Maven Wrapper"
        maven = "./mvnw -B"
    }
    sh "${maven} ${goals}"
}

/**
 * Get version from pom.xml
 */
def getVersion() {
    String pomData = readMavenPom file: 'pom.xml'
    def splitData = pomData.split(":")
    if (splitData.size() == 4) {
        splitData[3]
    } else {
        splitData[3]
    }
}

/**
 * Get artifact name
 */
def getName() {
    String pomData = readMavenPom file: 'pom.xml'
    def splitData = pomData.split(":")
    if (splitData.size() == 4) {
        splitData[1]
    } else {
        splitData[1]
    }

}

/*  Reads pom for name and version. */
/**
 * Get artifact name and version.
 */
def readNameAndVersion() {
    def pomFileText
    def pomXmlData
    String appName
    String appVersion
    def checkPom = fileExists "pom.xml"
    if (!checkPom) {
        throw new Exception("Unable to find pom.xml in specified directory.")
    }
    pomFileText = readFile "pom.xml"
    pomXmlData = new XmlSlurper().parseText(pomFileText)
    appName = pomXmlData.name.text()
    appVersion = pomXmlData.version.text()
    return ["name": appName, "version": appVersion]
}

def readArtifactAndVersion() {
    def pomFileText
    def pomXmlData
    String appName
    String appVersion
    def checkPom = fileExists "pom.xml"
    if (!checkPom) {
        throw new Exception("Unable to find pom.xml in specified directory.")
    }
    pomFileText = readFile "pom.xml"
    pomXmlData = new XmlSlurper().parseText(pomFileText)
    appName = pomXmlData.artifactId.text()
    appVersion = pomXmlData.version.text()
    return [appName, appVersion]

}

/**
 * Reads pom and check for the version tag retrun true if it exist
 */

def isVersionExist(fileName) {
    def pomFileText
    def pomXmlData
    String appName
    String appVersion
    boolean isVersionExist = false
    def checkPom = fileExists(fileName)
    if (!checkPom) {
        throw new Exception("Unable to find pom.xml in specified directory.")
    }
    pomFileText = readFile(fileName)
    pomXmlData = new XmlSlurper().parseText(pomFileText)

    appParentVersion = pomXmlData.version.text()
    if (appParentVersion?.trim())
        isVersionExist = true
    println("Is version exist - ${isVersionExist}")
    return isVersionExist

}

/**
 * Reads pom and check for the version tag retrun version
 */
def getVersionName(fileName) {
    def newPomFileText
    def newPomXmlData
    def parentPomVersion
    String appPomVersion
   
    def checkPom = fileExists(fileName)
    if (!checkPom) {
        throw new Exception("Unable to find pom.xml in specified directory.")
    }
    newPomFileText = readFile(fileName)
    newPomXmlData = new XmlSlurper().parseText(newPomFileText)
    parentPomVersion = newPomXmlData.parent.version.text()
    appPomVersion = newPomXmlData.version.text()
    println("Parent Pom Version - ${parentPomVersion}")
    // Add -SNAPSHOT to artifact pom version if parent pom version is 19.0 or 19.1 and does not contain -SNAPSHOT
     if((parentPomVersion == '19.0' || parentPomVersion == '19.1') && !appPomVersion.contains('-SNAPSHOT')){
        appPomVersion = appPomVersion + '-SNAPSHOT'
     }    
    println("Artifact Version - ${appPomVersion}")
    return appPomVersion
}

/**
 * Determine if Maven wrapper file is available or not.
 */
boolean wrapperAvailable() {
    return fileExists('./mvnw')
}

3-JavaDeployModuleTest

class JavaDeployModuleTest extends BasePipelineTest{

  def deployHelper;
  def test_env = [:]
  def dbVar = [:]

  @Before
  void setUp() throws Exception{
    scriptRoots += 'vars'
    super.setUp()
    deployHelper = loadScript("vars/javaDeployModule.groovy")
   // logHelper = loadScript("vars/logError.groovy")
    getBinding().setVariable("env", test_env)
    getBinding().setVariable("COUCHBASE_ADMINISTRATOR_USERNAME", "test")
    getBinding().setVariable("COUCHBASE_ADMINISTRATOR_PASSWORD", "test")
    helper.registerAllowedMethod('updateDB', [Object], { String str -> "Java_Deploy" })
   // helper.registerAllowedMethod('mavenUtils.getVersionName', [Object], { String str -> "pom.xml" })
    helper.registerAllowedMethod("ansiColor", [String.class, Closure.class], { l, c -> c() })
    helper.registerAllowedMethod("fileExists", [String.class], { f -> true  })
    // helper.registerAllowedMethod('log', [Object],{ String msg -> println(msg) })
    helper.registerAllowedMethod('mavenUtils.getVersionName', [String], null)
  }

  @Test
  void testBootUpcouchBaseSuccess() {
    def body = {
      put('versionNumber', "1.0.0")
      put('pomLocation', "Test")
    }

    def result  =deployHelper(body);
    System.out.println("result         "+result)
  }

When trying to run the test case its complaining about `log` and 'MavenUtil' . I tried to mock them but no luck. Getting below error-
error>>>>>>>>>>>No such property: mavenUtils for class: javaDeployModule

No such property: log for class: javaDeployModule
groovy.lang.MissingPropertyException: No such property: log for class: javaDeployModule
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at javaDeployModule.call(javaDeployModule.groovy:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaMethod$doMethodInvoke.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.callMethod(PipelineTestHelper.groovy:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.invokeMethod(PipelineTestHelper.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)

**Comment by caseyscarborough** [comment]
@waytoharish I was able to resolve this by doing something like the following:

```groovy
// vars/foo.groovy

def call(config=[:]) {
  // do some work
  // ...
  bar.doSomething()
}
```

```groovy
// vars/bar.groovy

def doSomething() {
  // do something
}
```

And then in your test:

```groovy
def foo = loadScript('vars/foo.groovy')
foo.bar = loadScript('vars/bar.groovy')
def output = foo.call()
```

It would be nice to be able to mock the calls instead of calling the actual script, but I haven't been able to figure that out.
