### ISSUE TITLE
loadInlineScript is broken? TestInlineScript.groovy missing @Test 

### ISSUE THREAD

**Issue by chgans** [jenkinsci/JenkinsPipelineUnit#408]
### Version report

`com.lesfurets:jenkins-pipeline-unit:1.10`

### Reproduction steps

- Step 1:

Reproduce src/test/groovy/com/lesfurets/jenkins/TestInlineScript.groovy, but add the `@Test`:
```
import org.junit.Before
import org.junit.Test
import com.lesfurets.jenkins.unit.BasePipelineTest

class ScratchTests extends BasePipelineTest {

    @Override
    @Before
    void setUp() throws Exception {
        super.setUp()
    }

    @Test
    void load_inline_script_with_simple_commands() {
        def script = loadInlineScript('''
            node {
                echo 'Test'
            }
        ''')

        script.run()

        printCallStack()
        assertJobStatusSuccess()
    }

    @Test
    void run_inline_script_with_simple_commands() {
        runInlineScript('''
            node {
                echo 'Test'
            }
        ''')

        printCallStack()
        assertJobStatusSuccess()
    }
}
```

- Step 2:

Run the test

### Results

Expected result: Test passes
Actual result: Test fails to execute

```
> Task :compileJava NO-SOURCE
> Task :compileGroovy UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrument SKIPPED
> Task :copyCoberturaDatafile SKIPPED
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test FAILED

No such property: helper for class: com.lesfurets.jenkins.unit.PipelineTestHelper
groovy.lang.MissingPropertyException: No such property: helper for class: com.lesfurets.jenkins.unit.PipelineTestHelper
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.loadInlineScript(PipelineTestHelper.groovy:426)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$loadInlineScript$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.lesfurets.jenkins.unit.BasePipelineTest.loadInlineScript(BasePipelineTest.groovy:344)
	at com.lesfurets.jenkins.unit.BasePipelineTest$loadInlineScript.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.navico.neon.devops.ScratchTests.load_inline_script_with_simple_commands(ScratchTests.groovy:30)
```

Looking at the source code, all the tests are missing `@Test`, so these tests are not actually run.
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/test/groovy/com/lesfurets/jenkins/TestInlineScript.groovy#L33

**Comment by RecuencoJones** [comment]
Hi @chgans!
Thanks for reporting this, completely missed the `@Test` annotations 😩 
Already looking into it for fixing
