### ISSUE TITLE
Unable to test errror method in a library

### ISSUE THREAD

**Issue by noorul** [jenkinsci/JenkinsPipelineUnit#479]
### Jenkins and plugins versions report

I am working on unit test.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Unit test

### Reproduction steps

I have library file `vars/log.groovy` with the following contents

```groovy
def info(message) {
    echo "[INFO] $message"
}

def warning(message) {
    echo "[WARNING] $message"
}

def error(message) {
    echo "[ERROR] $message"
}

def debug(message) {
    echo "[DEBUG] $message"
}
```

I have a test file `TestLogBroken` with following contents

```groovy
import static com.lesfurets.jenkins.unit.MethodCall.callArgsToString
import static org.junit.Assert.assertTrue

import com.lesfurets.jenkins.unit.BasePipelineTest
import org.junit.Before
import org.junit.Test

class TestLogBroken extends BasePipelineTest {
    def script

    @Override
    @Before
    void setUp() throws Exception {
        super.setScriptRoots(".", "vars")
        super.setUp()
        script = loadScript("log.groovy")
    }

    @Test
    void testError() throws Exception {
        script.error("ERROR")
        printCallStack()
        assertTrue(helper.callStack.findAll { call ->
            call.methodName == "echo"
        }.any { call ->
                callArgsToString(call).contains("[ERROR]")
            })
        assertJobStatusSuccess()
    }
}
```

### Expected Results

I expect the test to pass

### Actual Results

Test is failing with following error:

```log
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestLogBroken
   log.error(message ERROR)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.431 sec <<< FAILURE!
testErro(TestLogBroken)  Time elapsed: 0.88 sec  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.junit.Assert$assertTrue.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:206)
        at TestLogBroken.testErro(TestLogBroken.groovy:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testErro(TestLogBroken)

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

### Anything else?

Looks like `script.error(..)` is not invoking the error method that is defined in `log.groovy`. Maybe the instance that `loadScript()` returns already has `error` attribute. I am not sure how to take it forward and fix this.

**Comment by nre-ableton** [comment]
The problem might be that you are shadowing the Jenkins [`error` pipeline step](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#error-error-signal). That said, there is a mock registered for the `error` step: https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L167.

At any rate, I would advise you to rename this method so as not to cause potential confusion with the pipeline step of the same name.

**Comment by noorul** [comment]
I ended up naming it as err()
