### ISSUE TITLE
MissingPropertyException when trying to mock shared library method

### ISSUE THREAD

**Issue by FallDownT** [jenkinsci/JenkinsPipelineUnit#496]
I’m trying to use Jenkins Pipeline Unit to mock a method within my Jenkins shared library global variables (i.e. vars/ area) that **isn’t** a call method.  When I try this, I get a `MissingPropertyException`.

Here is a short, self-contained example of code in which I’m seeing this issue:
```groovy
// vars/foo.groovy
Integer call(Integer number) {
   Integer utilReturn = utils.addOne(number)  // This line is listed in MissingPropertyException stack
   return utilReturn
}
```
```groovy
// vars/utils.groovy
def funA() { ... }

Integer addOne(Integer start) { return start + 1 }

def funB() { ... }
```
```groovy
// test/groovy/FooTests.groovy
import com.lesfurets.jenkins.unit.BasePipelineTest
import org.junit.jupiter.api.*

class FooTests extends BasePipelineTest {
   private static final Integer MOCKED_RESULT = 7
   private Script fooScript

   @Override
   @BeforeEach
   void setUp()
   {
      super.setUp()
      this.fooScript = loadScript('vars/foo.groovy')
      helper.registerAllowedMethod('utils.addOne', [Integer.class], { return MOCKED_RESULT })
   }

   @Test
   void testMockingUtilsAddOne() {
      Integer expectedResult = MOCKED_RESULT
      Integer actualResult = this.fooScript.call(12)  // This results in MissingPropertyException
      Assertions.assertEquals(expectedResult, actualResult)
   }
}
```

When I try running this test, I get the following exception:
```
groovy.lang.MissingPropertyException: No such property: utils for class: foo
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
    at foo.call(foo.groovy:3)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaMethod$doMethodInvoke.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
    at com.lesfurets.jenkins.unit.PipelineTestHelper.callMethod(PipelineTestHelper.groovy:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
    at com.lesfurets.jenkins.unit.PipelineTestHelper$_closure3.doCall(PipelineTestHelper.groovy:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:84)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
    at FooTests.testMockingUtilsAddOne (FooTests.groovy:21)
```

How can I modify this code so that I can mock the `utils.addOne(…)` call in my test?  Thanks in advance for your help!

### Troubleshooting
While troubleshooting, I tried printing `helper.callStack` after catching the `MissingPropertyException` and didn’t see a call to `utils.addOne(...)` in there.

### Similar Issues
I believe this issue is similar to #357, but I was not able to figure out how to get my scenario working from reading through this issue.

**Comment by nre-ableton** [comment]
The problem here comes from having singletons with dependencies on each other. This is why I usually recommend putting all pipeline library logic in proper classes, and having the singletons just be convenience passthru layers. See [this comment](https://github.com/jenkinsci/JenkinsPipelineUnit/issues/308#issuecomment-707078194) for more details.

Anyways, if that type of refactoring is inconvenient, you can fix it by registering `utils` directly on `foo`:

```groovy
// test/groovy/FooTests.groovy
import com.lesfurets.jenkins.unit.BasePipelineTest
import org.junit.jupiter.api.*

class FooTests extends BasePipelineTest {
   private static final Integer MOCKED_RESULT = 7
   private Script fooScript

   @Override
   @BeforeEach
   void setUp()
   {
      super.setUp()
      this.fooScript = loadScript('vars/foo.groovy')
      fooScript.utils = loadScript('vars/utils.groovy')
   }
```

I haven't tested the above pseudocode, but something like that should work.

**Comment by FallDownT** [comment]
Thanks for the quick response, @nre-ableton!  My biggest issue with putting pipeline library logic in classes has been that I wasn't sure how to access other pipeline steps from classes.  Reading through [your comment](https://github.com/jenkinsci/JenkinsPipelineUnit/issues/308#issuecomment-707078194), I see how this can be done easily by accessing them through a passed script context object.
Thanks for both solutions!  I'll post later about how my refactor goes.

**Comment by FallDownT** [comment]
My refactor went successfully and I really prefer being able to encapsulate my business logic in classes rather than global variable methods.  Thanks for all your help, @nre-ableton!!

**Comment by nre-ableton** [comment]
@FallDownT glad to hear that you got it working! :tada:
