### ISSUE TITLE
Dependency on java.lang.Module prevents pipeline tests from running on Java 8

### ISSUE THREAD

**Issue by den1ska** [jenkinsci/JenkinsPipelineUnit#549]
I tried to run the following test

```class TestInlineScript extends BasePipelineTest {

  @Before
  void setUp() {
    super.setUp()
  }

  @Test
  void simple_test_checks_job() {
    def script = loadInlineScript('''
      node {
        stage('test') {
          sh 'exit 1'
        }
      }
    ''')
    script.run()
    printCallStack()
    assertJobStatusSuccess()
  }

}
```

which fails with

```
2022-08-09T17:19:34.002+0300 [DEBUG] [TestEventLogger] TestInlineScript > simple_test_checks_job FAILED
2022-08-09T17:19:34.002+0300 [DEBUG] [TestEventLogger]     java.lang.NoClassDefFoundError: java/lang/Module
2022-08-09T17:19:34.002+0300 [DEBUG] [TestEventLogger]         at java.lang.Class.getDeclaredMethods0(Native Method)
2022-08-09T17:19:34.002+0300 [DEBUG] [TestEventLogger]         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
2022-08-09T17:19:34.003+0300 [DEBUG] [TestEventLogger]         at java.lang.Class.privateGetPublicMethods(Class.java:2902)
2022-08-09T17:19:34.003+0300 [DEBUG] [TestEventLogger]         at java.lang.Class.getMethods(Class.java:1615)
2022-08-09T17:19:34.003+0300 [DEBUG] [TestEventLogger]         at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336)
2022-08-09T17:19:34.003+0300 [DEBUG] [TestEventLogger]         at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)
2022-08-09T17:19:34.003+0300 [DEBUG] [TestEventLogger]         at java.beans.Introspector.getBeanInfo(Introspector.java:426)
2022-08-09T17:19:34.003+0300 [DEBUG] [TestEventLogger]         at java.beans.Introspector.getBeanInfo(Introspector.java:173)

... skipped

2022-08-09T17:19:34.013+0300 [DEBUG] [TestEventLogger]         java.lang.ClassNotFoundException: java.lang.Module
2022-08-09T17:19:34.013+0300 [DEBUG] [TestEventLogger]             at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
2022-08-09T17:19:34.013+0300 [DEBUG] [TestEventLogger]             at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2022-08-09T17:19:34.013+0300 [DEBUG] [TestEventLogger]             at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2022-08-09T17:19:34.013+0300 [DEBUG] [TestEventLogger]             at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2022-08-09T17:19:34.013+0300 [DEBUG] [TestEventLogger]             ... 89 more

```

The problem reproduces against all versions starting from 1.15. However, when I build the `jenkins-pipeline-unit.jar` myself the issue disappears and everything works as expected. I did diff between my jar and one loaded from maven repository and found that the only `com/lesfurets/jenkins/unit/InterceptingGCL.class` differs. Here's the output from `java -p`
```
Compiled from "InterceptingGCL.groovy"
public class com.lesfurets.jenkins.unit.InterceptingGCL extends groovy.lang.GroovyClassLoader implements groovy.lang.GroovyObject {
  public static transient boolean __$stMC;
  public com.lesfurets.jenkins.unit.InterceptingGCL(com.lesfurets.jenkins.unit.PipelineTestHelper, java.lang.ClassLoader, org.codehaus.groovy.control.CompilerConfiguration, groovy.lang.Binding);
  public static void interceptClassMethods(groovy.lang.MetaClass, com.lesfurets.jenkins.unit.PipelineTestHelper, groovy.lang.Binding);
  public static groovy.lang.Closure defaultClosure(java.lang.Class...);
  public java.lang.Class parseClass(groovy.lang.GroovyCodeSource, boolean) throws org.codehaus.groovy.control.CompilationFailedException;
  public java.lang.Class<?> loadClass(java.lang.String) throws java.lang.ClassNotFoundException;
  protected groovy.lang.MetaClass $getStaticMetaClass();
  public groovy.lang.MetaClass getMetaClass();
  public void setMetaClass(groovy.lang.MetaClass);
  public java.lang.Object invokeMethod(java.lang.String, java.lang.Object);
  public java.lang.Object getProperty(java.lang.String);
  public void setProperty(java.lang.String, java.lang.Object);
  public com.lesfurets.jenkins.unit.PipelineTestHelper getHelper();
  public void setHelper(com.lesfurets.jenkins.unit.PipelineTestHelper);
  public groovy.lang.Binding getBinding();
  public void setBinding(groovy.lang.Binding);
  public java.lang.Class super$5$loadClass(java.lang.String);
  public java.lang.Class super$5$loadClass(java.lang.String, boolean);
  public java.lang.Class super$2$loadClass(java.lang.Module, java.lang.String);
  public java.lang.Class super$5$loadClass(java.lang.String, boolean, boolean);
  public java.lang.Class super$5$loadClass(java.lang.String, boolean, boolean, boolean);
  public java.lang.Class super$5$parseClass(java.lang.String);
  public java.lang.Class super$5$parseClass(java.lang.String, java.lang.String);
  public java.lang.Class super$5$parseClass(java.io.InputStream, java.lang.String);
  public java.lang.Class super$5$parseClass(java.io.File);
  public java.lang.Class super$5$parseClass(groovy.lang.GroovyCodeSource);
  public java.lang.Class super$5$parseClass(groovy.lang.GroovyCodeSource, boolean);
}
```
As you can see there's a method `public java.lang.Class super$2$loadClass(java.lang.Module, java.lang.String);` in the generated class which brings an unwanted dependency into the code.

I suspect there might be an issue with the build host which uses Java 9+.

**Comment by nre-ableton** [comment]
As Java 11 is the [minimum supported version](https://www.jenkins.io/doc/administration/requirements/java/) for Jenkins, the same should also be true for this framework. However, I can see that the documentation hasn't been updated, so apologies for that. I'll update the documentation, but in the meantime, the solution is to use JDK 11 or newer.

**Comment by den1ska** [comment]
Thank you for the quick response. I'm closing this as not an issue.
