### ISSUE TITLE
NoClassDefFoundError java/lang/Module with 1.15 & 1.16

### ISSUE THREAD

**Issue by juanpablo-santos** [jenkinsci/JenkinsPipelineUnit#554]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.346.3
OS: Linux - 3.10.0-1160.71.1.el7.x86_64
---
Office-365-Connector:4.17.0
ace-editor:1.1
all-changes:1.5
analysis-model-api:10.16.1
ansicolor:1.0.2
ant:475.vf34069fef73c
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
authentication-tokens:1.4
authorize-project:1.4.0
badge:1.9.1
basic-branch-build-strategies:1.3.2
blueocean:1.25.7
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.7
blueocean-commons:1.25.7
blueocean-config:1.25.7
blueocean-core-js:1.25.7
blueocean-dashboard:1.25.7
blueocean-display-url:2.4.1
blueocean-events:1.25.7
blueocean-git-pipeline:1.25.7
blueocean-github-pipeline:1.25.7
blueocean-i18n:1.25.7
blueocean-jira:1.25.7
blueocean-jwt:1.25.7
blueocean-personalization:1.25.7
blueocean-pipeline-api-impl:1.25.7
blueocean-pipeline-editor:1.25.7
blueocean-pipeline-scm-api:1.25.7
blueocean-rest:1.25.7
blueocean-rest-impl:1.25.7
blueocean-web:1.25.7
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.0-1
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-failure-analyzer:2.4.0
build-history-metrics-plugin:97.vdcf3aa48af8d
build-metrics:1.3
build-monitor-plugin:1.13+build.202205140447
build-pipeline-plugin:1.5.8
build-timeout:1.24
build-user-vars-plugin:1.8
buildgraph-view:1.8
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
changes-since-last-success:0.6
checks-api:1.7.5
chucknorris:1.4
claim:495.v01a_c6fb_2b_a_7a
cloudbees-bitbucket-branch-source:791.vb_eea_a_476405b
cloudbees-disk-usage-simple:170.va_fd5b_4ee6858
cloudbees-folder:6.740.ve4f4ffa_dea_54
cluster-stats:0.4.6
command-launcher:84.v4a_97f2027398
commons-lang3-api:3.12.0-36.vd97de6465d5b_
compact-columns:1.148.v649c8db_2a_91e
conditional-buildstep:1.4.2
config-file-provider:3.11.1
conjur-credentials:1.0.12
console-tail:15.vc54cb_4ca_6981
coordinator:1.4.0
copyartifact:1.47
countjobs-viewstabbar:1.0.1
credentials:1143.vb_e8b_b_ceee347
credentials-binding:523.vd859a_4b_122e6
cvs:2.19.1
dark-theme:245.vb_a_2b_b_010ea_96
dashboard-view:2.447.vda_124dd35f11
data-tables-api:1.12.1-3
disk-usage:0.28
display-url-api:2.3.6
docker-commons:1.21
docker-java-api:3.2.13-37.vf3411c9828b9
docker-plugin:1.2.9
docker-slaves:1.0.7
docker-workflow:521.v1a_a_dd2073b_2e
dropdown-viewstabbar-plugin:1.7
dtkit-api:3.0.1
durable-task:500.v8927d9fd99d8
echarts-api:5.3.3-1
email-ext:2.91
embeddable-build-status:255.va_d2370ee8fde
envinject:2.875.v9b_9e962da_a_ec
envinject-api:1.199.v3ce31253ed13
extended-choice-parameter:346.vd87693c5a_86c
extended-read-permission:3.2
extensible-choice-parameter:1.8.0
external-monitor-job:192.ve979ca_8b_3ccd
favorite:2.4.1
font-awesome-api:6.1.2-1
forensics-api:1.15.1
generic-webhook-trigger:1.84
git:4.11.5
git-client:3.11.2
git-parameter:0.9.17
git-server:1.11
github:1.34.5
github-api:1.303-400.v35c2d8258028
github-branch-source:1687.v7618247e672d
gitlab-plugin:1.5.35
global-build-stats:244.v27c8a_2e50a_34
gogs-webhook:1.0.15
google-oauth-plugin:1.0.6
google-play-android-publisher:4.2
greenballs:1.15.1
groovy:442.v817e6d937d6c
groovy-postbuild:2.5
h2-api:1.4.199
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
hp-application-automation-tools-plugin:7.4.3
htmlpublisher:1.30
http_request:1.16
internetmeme:1.0
ionicons-api:24.va_745a_b_a_97fc3
jackson2-api:2.13.3-285.vc03c0256d517
jakarta-activation-api:2.0.1-1
jakarta-mail-api:2.0.1-1
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-4
javax-mail-api:1.6.2-7
jaxb:2.3.6-1
jdk-tool:55.v1b_32b_6ca_f9ca
jenkins-design-language:1.25.7
jenkins-jira-plugin:3.11.1
jenkinswalldisplay:0.6.34
jersey2-api:2.36-2
jira:3.8
jira-steps:2.0.141.vd0c6e6dc83f0
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.15-1
jobConfigHistory:1171.v04b_66d78555e
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-4
jsch:0.1.55.61.va_e9ee26616e7
junit:1119.1121.vc43d0fc45561
kubernetes-cli:1.10.3
kubernetes-client-api:5.12.2-193.v26a_6078f65a_9
kubernetes-credentials:0.9.0
lastfailureversioncolumn:1.1
lastsuccessdescriptioncolumn:1.0
lastsuccessversioncolumn:1.1
ldap:2.12
lockable-resources:2.16
mailer:435.v79ef3972b_5c7
mapdb-api:1.0.9.0
matrix-auth:3.1.5
matrix-project:772.v494f19991984
maven-artifact-choicelistprovider:1.11.0
maven-plugin:3.19
mercurial:1251.va_b_121f184902
metrics:4.2.10-389.v93143621b_050
mina-sshd-api-common:2.8.0-36.v8e25ce90d4b_1
mina-sshd-api-core:2.8.0-36.v8e25ce90d4b_1
momentjs:1.1.1
monitoring:1.91.0
naginator:1.18.1
nexus-jenkins-plugin:3.14.431.v37ca_dc788b_b_1
nodelabelparameter:1.11.0
nodenamecolumn:1.2
oauth-credentials:0.5
okhttp-api:4.9.3-108.v0feda04578cf
pam-auth:1.10
parameter-separator:1.3
parameterized-trigger:2.45
permissive-script-security:0.7
pipeline-aggregator-view:1.11
pipeline-build-step:2.18
pipeline-config-history:1.6
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:612.v84da_9c54906d
pipeline-input-step:449.v77f0e8b_845c4
pipeline-maven:1195.v3b_a_d1b_e792e0
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2114.v2654ca_721309
pipeline-model-definition:2.2114.v2654ca_721309
pipeline-model-extensions:2.2114.v2654ca_721309
pipeline-multibranch-defaults:2.1
pipeline-npm:0.9.2
pipeline-rest-api:2.24
pipeline-stage-step:296.v5f6908f017a_5
pipeline-stage-tags-metadata:2.2114.v2654ca_721309
pipeline-stage-view:2.24
pipeline-utility-steps:2.13.0
plain-credentials:139.ved2b_9cf7587b
plugin-util-api:2.17.0
poll-mailbox-trigger-plugin:1.026
popper-api:1.16.1-3
popper2-api:2.11.6-1
postgresql-api:42.3.3
prism-api:1.28.0-2
progress-bar-column-plugin:1.0
prometheus:2.0.11
promoted-builds:892.vd6219fc0a_efb
pubsub-light:1.16
purge-build-queue-plugin:48.v39c52a_26a_264
readonly-parameters:1.0.0
resource-disposer:0.20
role-strategy:561.v9846c7351a_41
run-condition:1.5
saml:2.333.vc81e525974a_c
schedule-build:345.vc2d8f6ef9182
scm-api:621.vda_a_b_055e58f7
scm-filter-branch-pr:0.5.1
script-security:1175.v4b_d517d6db_f0
show-build-parameters:1.0
simple-theme-plugin:103.va_161d09c38c7
slack:616.v03b_1e98d13dd
snakeyaml-api:1.31-84.ve43da_fb_49d0b
sonar:2.14
sse-gateway:1.25
ssh:2.6.1
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:305.v8f4381501156
ssh-slaves:1.834.v622da_57f702c
ssh-steps:2.0.39.v831c5e6468b_c
sshd:3.242.va_db_9da_b_26a_c3
structs:324.va_f5d6774f3a_d
subversion:2.16.0
theme-manager:1.5
timestamper:1.19
token-macro:308.v4f2b_ed62b_b_16
translation:1.16
trilead-api:1.67.vc3938a_35172f
validating-string-parameter:2.8
variant:59.vf075fe829ccb
versioncolumn:2.2
versionnumber:1.9
view-job-filters:2.3
warnings-ng:9.18.0
webhook-step:173.vfa_b_93560b_977
windows-slaves:1.8.1
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1192.v2d0deb_19d212
workflow-basic-steps:994.vd57e3ca_46d24
workflow-cps:2759.v87459c4eea_ca_
workflow-cps-global-lib:588.v576c103a_ff86
workflow-durable-task-step:1199.v02b_9244f8064
workflow-job:1207.ve6191ff089f8
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:838.va_3a_087b_4055b
ws-cleanup:0.43
xfpanel:2.0.1
xunit:3.1.0
xvfb:1.2
xvnc:1.28
  ```
Also, lots of plugins, although not clear why this is required pipelines, 
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

ubuntu 22 with latest maven

### Reproduction steps

Test classes which inherit from BasePipelineTest having something like:

```
    @BeforeEach
    void setUp() throws Exception {
        super.setUp()
        registerCommonMockSteps()
    }
```
was succesfully executing until migrating jenkins-pipeline-unit to 1.15, when we get an NoClassDefFoundError java.lang.Module

### Expected Results

successfully call `BasePipelineTest.setup()`

### Actual Results

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.132 s <<< FAILURE! - in org.corp.jenkins.pipelines.PipelineTest
org.corp.jenkins.pipelines.PipelineTest.should get events  Time elapsed: 0.038 s  <<< ERROR!
java.lang.NoClassDefFoundError: java/lang/Module
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336)
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)
	at java.beans.Introspector.getBeanInfo(Introspector.java:426)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3313)
	at java.security.AccessController.doPrivileged(Native Method)
	at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3311)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3288)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:260)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:302)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:261)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:883)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:87)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:271)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.init(PipelineTestHelper.groovy:407)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$init$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.lesfurets.jenkins.unit.BasePipelineTest.initHelper(BasePipelineTest.groovy:113)
	at com.lesfurets.jenkins.unit.BasePipelineTest.setUp(BasePipelineTest.groovy:103)
[...]
```

### Anything else?

seems related to changes introduced in #510. Aforementioned stacktrace happens when testing the pipelines with maven, having set up the JDK to 1.8 (via toolchain and with `JAVA_HOME` + `PATH`), groovy-eclipse-batch compiler version being 2.4.21-01, with following dependencies:
* jenkins-core: 2.277.4
* groovy-cps 1.32
* workflow-basic-steps 2.23
* jenkins-pipeline-unit 1.14 (everything ok), 1.15 (stacktrace), 1.16 (stacktrace)

**Comment by nre-ableton** [comment]
JDK 8 is no longer supported, you need at least JDK 11. Can you try to reproduce with JDK 11?

**Comment by juanpablo-santos** [comment]
Hi @nre-ableton !

I've just seen that I missed #552 which was merged a bit before this issue. We're not using latest LTS (first mandating JDK11), so our pipelines are still JDK8. Luckily, by using toolchains we can easily compile with JDK8 and execute the tests with JDK11, which makes this issue go away. Please feel free to label it as not a bug.


thanks & best regards

**Comment by smmckay** [comment]
This issue was bugging me so I dug in to figure out what was going on. Building master with JDK 11 results in InterceptingGCL referencing java.lang.Module, and building it with JDK 8 doesn't. That explains the immediate cause, but why should it matter what we build with? InterceptingGCL doesn't mention Module anywhere in the source.

The root cause is groovyc. Whenever a class makes a method call through super, groovyc generates stub methods to handle the call. This is needed to support MOP. Crucially this stub generation is _name-based_ and creates stubs for all overloads of the called method! In this case what happened is Java 9 introduced an overload for loadClass() that has a Module parameter. Groovyc duly copies that signature to InterceptingGCL and breaks back compat.
