### ISSUE TITLE
Failing to test a pipeline library

### ISSUE THREAD

**Issue by vmassol** [jenkinsci/JenkinsPipelineUnit#77]
Hi guys,

Thanks for this framework which seems very nice but I'm failing to use it right now. So I have a pipeline library located in /vars/xwikiModule.groovy (content can be seen at https://github.com/xwiki/xwiki-jenkins-pipeline/blob/master/vars/xwikiModule.groovy) and I'm trying to test it using this unit test:

```java
package org.xwiki.jenkins.test;

import java.io.File;

import org.junit.BeforeClass;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import com.lesfurets.jenkins.unit.cps.BasePipelineTestCPS;
import com.lesfurets.jenkins.unit.global.lib.LibraryConfiguration;

import static com.lesfurets.jenkins.unit.global.lib.LocalSource.*;
import static com.lesfurets.jenkins.unit.global.lib.LibraryConfiguration.*;

public class PipelineTest extends BasePipelineTestCPS
{
    @ClassRule
    public static TemporaryFolder tmpFolder = new TemporaryFolder();

    private static File temp;

    @BeforeClass
    public static void init() throws Exception
    {
        temp = tmpFolder.newFolder("xwiki");
    }

    @Test
    public void execute() throws Exception
    {
        super.setUp();

        LibraryConfiguration library = library()
            .name("XWiki")
            .retriever(localSource("/Users/vmassol/dev/xwiki/xwiki-jenkins-pipeline/vars/xwikiModule.groovy"))
            .targetPath(temp.getPath())
            .defaultVersion("master")
            .allowOverride(true)
            .implicit(true)
            .build();
        getHelper().registerSharedLibrary(library);

        loadScript("example.jenkins");
        printCallStack();
    }
}
```

The `example.jenkins` file contains:

```
@Library("XWiki@master")

xwikiModule {
}
```

It's failing with:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/Users/vmassol/dev/xwiki/xwiki-jenkins-pipeline/example.jenkins: 23: unexpected token: xwikiModule @ line 23, column 1.
   xwikiModule {
   ^

1 error


	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:360)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:145)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:111)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:237)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:167)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:931)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:256)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:243)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:212)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:566)
	at groovy.util.GroovyScriptEngine$loadScriptByName$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.loadScript(PipelineTestHelper.groovy:323)
```

Anyone what I'm doing wrong? thanks!

**Comment by stchar** [comment]
Hi, I believe your `.retriever(localSource(path))` is precision too much. 
You should provide path to the root folder of the library. I guess it's `/Users/vmassol/dev/xwiki/xwiki-jenkins-pipeline/`.

**Comment by stchar** [comment]
@vmassol ,  please reopen if you still have an issue.
