### ISSUE TITLE
Q: How do I load other plugin dependencies within the sharedlibrary to be use when testing it?

### ISSUE THREAD

**Issue by v1v** [jenkinsci/JenkinsPipelineUnit#78]
Hi there,

I'm getting some errors when running JenkinsPipelineUnit using a 'shared-library' which imports other dependencies, let me explain you:

**Console output when running ./gradlew test**
``` 
/Users/victor/work/v1v/rosie-libs/build/libs/my-libs@master/vars/commons.groovy: 6: unable to resolve class org.jenkinsci.plugins.pipeline.utility.steps.conf.mf.SimpleManifest
 @ line 6, column 1.
   import org.jenkinsci.plugins.pipeline.utility.steps.conf.mf.SimpleManifest
```

Then I do have a commons variable under vars/, see below

**vars/commons.groovy**
``` java
/**
 * Common methods shared among all the workflows
 */

import com.cloudbees.groovy.cps.NonCPS
import org.jenkinsci.plugins.pipeline.utility.steps.conf.mf.SimpleManifest
import org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper
...
```

Gradle dependencies are explicitly set as below

**build.gradle dependencies**
``` gradle
dependencies {
    compile 'org.slf4j:slf4j-api:1.7.22'
    compile 'org.codehaus.groovy:groovy-all:2.4.7'
    compile group: 'org.jenkins-ci.plugins.workflow', name: 'workflow-support', version: '2.16'

    testCompile group:'com.lesfurets', name:'jenkins-pipeline-unit', version:'1.1'
    testCompile group: 'junit', name: 'junit', version: '4.11'
    testCompile group: 'org.jenkins-ci.plugins.workflow', name: 'workflow-support', version: '2.16'
}
```

Test class as below 

``` java
import static com.lesfurets.jenkins.unit.global.lib.LibraryConfiguration.library
import static com.lesfurets.jenkins.unit.global.lib.LocalSource.localSource

import org.junit.Before
import org.junit.Test

import com.lesfurets.jenkins.unit.BasePipelineTest
class TestJenkinsCommonLib extends BasePipelineTest {

    String sharedLibs = ''

    @Override
    @Before
    void setUp() throws Exception {
        scriptRoots += 'jobs'
        super.setUp()
        def library = library().name('my-libs')
                .defaultVersion("master")
                .allowOverride(true)
                .implicit(true)
                .targetPath('build/libs')
                .retriever(localSource('build/libs'))
                .build()
        helper.registerSharedLibrary(library)
    }

    @Test
    void should_execute_without_errors() throws Exception {
        def script = runScript("template/pipeline/template.groovy")
    }
``` 

**Template pipeline**
``` groovy
@Library('my-libs')
import com.test.LibHelper

gitlab_lib = new LibHelper(this)

node() {
    echo "Hello World!"
}

return this
```

**Class**
``` java
package com.test

class LibHelper implements Serializable {
    def script;
    LibHelper(script) {
        this.script=script
    }
```

Apparently when loading the library the above var/commons.groovy variable is evaluated and it failed even though when I'm testing something else, so, it looks like those gradle dependencies are not passed to the shared library, the full stacktrace:

``` 
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy12.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.lesfurets.jenkins.unit.global.lib.LibraryLoader.loadImplicitLibraries(LibraryLoader.groovy:37)
	at com.lesfurets.jenkins.unit.global.lib.LibraryAnnotationTransformer.call(LibraryAnnotationTransformer.groovy:41)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1053)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:591)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:256)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:243)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:211)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:568)
	at groovy.util.GroovyScriptEngine$loadScriptByName$0.call(Unknown Source)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.loadScript(PipelineTestHelper.groovy:323)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$loadScript$3.callCurrent(Unknown Source)
	at com.lesfurets.jenkins.unit.PipelineTestHelper.runScript(PipelineTestHelper.groovy:339)
	at com.lesfurets.jenkins.unit.PipelineTestHelper$runScript$2.call(Unknown Source)
	at com.lesfurets.jenkins.unit.BasePipelineTest.runScript(BasePipelineTest.groovy:111)
	at com.lesfurets.jenkins.unit.BasePipelineTest$runScript.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at TestJenkinsCommonLib.should_execute_without_errors(TestJenkinsCommonLib.groovy:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.lesfurets.jenkins.unit.global.lib.LibraryLoader$LibraryLoadingException: Error on loading library my-libs@master : startup failed:
```

Any ideas how I can load those dependencies when running the pipelineunit? Is that something to be done within the gradle project or some other actions?

Just to clarify, I expanded this [working project](https://github.com/stchar/pipeline-sharedlib-testharness.git) to use my shared libraries.

Thanks

**Comment by olivierGATSNCF** [comment]
hi v1v, 
i've the same issue with dependencies into my shared librarie. 
have you solve it?

**Comment by olivierGATSNCF** [comment]
In my case, it was due to a wrong src path in my shared libraries  src/main/java. directly in src it's better.

**Comment by stchar** [comment]
Hi @v1v, 
looks like you need to add `pipeline-utility-steps` plugin into your class path. It's pretty tricky.  
I used close approach in https://github.com/stchar/pipeline-dsl-seed/blob/master/build.gradle
see configuraions.testPlugins
Not sure if it would work for you.

**Comment by stchar** [comment]
Also you need to extend your `build.gradle` file with `resolveTestDslPlugins(){}` method and then you need to override `test` task. Let me know if you need any help.

**Comment by jamesalbert** [comment]
@stchar thanks for the links (I was having the exact same problem)

turns out specifying jar works, e.g.:
```
compile 'org.jenkins-ci.plugins:pipeline-utility-steps:1.5.1@jar'
```
worked for me. I'm not a java guy so I'm not why that worked but 🤷‍♂️

**Comment by stchar** [comment]
@jamesalbert 
good to know, thanks

**Comment by vinayk06** [comment]
@stchar I am trying to do something similar creating a gradle project similar to https://github.com/sheehan/job-dsl-gradle-example but somehow I am able to run the seed job when I have import or \@Library('....') it throws error library not found or cannot resolve the class, What changes do I  miss in jenkins configurations.?? Help is appreciated

**Comment by stchar** [comment]
Could you please share a test case and the stacktrace
