### ISSUE TITLE
 No signature of method: TestingClass.library() is applicable for argument

### ISSUE THREAD

**Issue by fabifrank** [jenkinsci/JenkinsPipelineUnit#82]
```
groovy.lang.MissingMethodException: No signature of method: TestingClass.library() is applicable for argument types: () values: []
    Possible solutions: every(), any()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:81)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158)
        at SlackNotificationIntegrationSpec.setUp(TestingClass.groovy:14)
```

While trying to instantiate the library for test like so:

```
def lib = library()
.name('lib-name')
.retriever(localSource('./'))
.targetPath(clonePath)
.defaultVersion("master")
.allowOverride(true)
.implicit(false)
.build()
helper.registerSharedLibrary(lib)   
```

**Comment by fabifrank** [comment]
Got it working like so:

```
import com.lesfurets.jenkins.unit.global.lib.LibraryConfiguration;
import com.lesfurets.jenkins.unit.global.lib.LocalSource
  class SlackNotificationIntegrationSpec extends BasePipelineTest {
  
      @Override
      @Before
      public void setUp() throws Exception {
          super.setUp();
          helper.registerAllowedMethod("slackSend", [Map.class], { "ok" });

def source = LocalSource.localSource('./');
def libDesc = new LibraryConfiguration();
libDesc.name = 'some-lib-name';                                                                                                          
libDesc.retriever = source;
libDesc.defaultVersion = '';
libDesc.allowOverride = true;
libDesc.implicit = false;
def lib = helper.registerSharedLibrary(libDesc)
...
```

**Comment by fabifrank** [comment]
Update - agnostic way:

```
import static com.lesfurets.jenkins.unit.global.lib.LibraryConfiguration.library;   
```
